# Generated by Django 6.0 on 2025-12-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('work', 'Work')], default='personal', max_length=10),
        ),
    ]
