# Generated by Django 6.0 on 2026-01-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='resumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
