# Generated by Django 6.0 on 2026-01-01 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0002_pomodorosession_paused_at_pomodorosession_resumed_at'),
        ('tasks', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorosession',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to='tasks.task'),
        ),
    ]
