# Generated by Django 6.0 on 2026-01-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0003_alter_pomodorosession_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosession',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='running', max_length=10),
        ),
    ]
