# Generated by Django 6.0 on 2026-01-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0004_pomodorosession_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodorosession',
            name='resumed_at',
        ),
        migrations.RemoveField(
            model_name='pomodorosession',
            name='status',
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='paused_duration_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
