# Generated by Django 6.0 on 2026-01-02 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0006_cleanup_active_sessions'),
        ('tasks', '0003_alter_task_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paused_at', models.DateTimeField()),
                ('resumed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pomodorosession',
            options={},
        ),
        migrations.AddConstraint(
            model_name='pomodorosession',
            constraint=models.UniqueConstraint(condition=models.Q(('completed', False), ('is_break', False)), fields=('user',), name='one_active_pomodoro_per_user'),
        ),
        migrations.AlterModelTable(
            name='pomodorosession',
            table=None,
        ),
        migrations.AddField(
            model_name='pomodoropause',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='pomodoro.pomodorosession'),
        ),
    ]
