# Generated by Django 6.0 on 2026-01-09 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0007_pomodoropause_alter_pomodorosession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorosession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
